---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backendk8s
  namespace: vault
spec:
  provider:
    vault:
      server: "https://vault.vault:8200"
      path: "secret"
      version: "v2"
      caProvider:
        # Can be Secret or ConfigMap
        type: "Secret"
        name: "vault-ha-tls"
        key: "vault.ca"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "example"
          serviceAccountRef:
            name: "default"

