apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: vault
  labels:
    app.kubernetes.io/name: openldap
spec:
  type: ClusterIP
  ports:
    - name: tcp-ldap
      port: 389
      targetPort: tcp-ldap
  selector:
    app.kubernetes.io/name: openldap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: vault
  labels:
    app.kubernetes.io/name: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      containers:
        - name: openldap
          image: osixia/openldap:1.4.0
          imagePullPolicy: "Always"
          env:
            - name: LDAP_ORGANISATION
              value: "learn"
            - name: LDAP_DOMAIN
              value: "learn.example"
            - name: LDAP_ADMIN_PASSWORD
              value: 2LearnVault
          ports:
            - name: tcp-ldap
              containerPort: 389