# kubectl create sa test -n vault111
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace: vault111
  name: example
spec:
  # required configuration
  # VaultConnectionRef of the corresponding VaultConnection CustomResource.
  # If no value is specified the Operator will default to the  VaultConnection,
  # configured in its own Kubernetes namespace.
  vaultConnectionRef: example
  # Method to use when authenticating to Vault.
  method: jwt
  # Mount to use when authenticating to auth method.
  mount: jwt
  # allowedNamespaces: []{"*"}
  # Kubernetes specific auth configuration, requires that the Method be set to kubernetes.
  jwt:
    # role to use when authenticating to Vault
    role: my-role3
    # ServiceAccount to use when authenticating to Vault
    # it is recommended to always provide a unique serviceAccount per Pod/application
    serviceAccount: default
    audiences: ["https://kubernetes.default.svc.cluster.local"]

  # optional configuration
  # Vault namespace where the auth backend is mounted (requires Vault Enterprise)
  # namespace: ""
  # Params to use when authenticating to Vault
  # params: []
  # HTTP headers to be included in all Vault authentication requests.
  # headers: []
